### ISSUE TITLE
android 11

### ISSUE THREAD

**Issue by ghost** [SA-17/Recovery_builder#8]
bro, i have android 11 device tree

but no have twrp_viva.mk only omni_viva.mk
so in manifest type aosp or omni
and in OT type aosp or omni

**Comment by SA-17** [comment]
> bro, i have android 11 device tree
> 
> but no have twrp_viva.mk only omni_viva.mk so in manifest type aosp or omni and in OT type aosp or omni

hi i fix all stuff today thanks for using our builder. about your problem you just adapt your tree to work with twrp-11 follow these steps:
1) rename everything to twrp (omni ---> twrp)
2) delete gsm flag on twrp_****.mk
